# Generated by Django 5.2.17 on 2026-08-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('full_path', models.TextField(unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('is_leaf', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.taxonomycategory')),
            ],
            options={
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='taxonomy.taxonomycategory')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('value', models.CharField(max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.taxonomyattribute')),
            ],
        ),
        migrations.AddConstraint(
            model_name='taxonomyattribute',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_attribute'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyvalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_value'),
        ),
    ]
