# Generated by Django 5.2.17 on 2026-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomyattribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='taxonomyvalue',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='taxonomyattribute',
            name='unique_category_attribute',
        ),
        migrations.RemoveConstraint(
            model_name='taxonomyvalue',
            name='unique_attribute_value',
        ),
        migrations.RenameField(
            model_name='taxonomyvalue',
            old_name='value',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='taxonomyattribute',
            name='category',
        ),
        migrations.AddField(
            model_name='taxonomyattribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='taxonomy.taxonomycategory'),
        ),
        migrations.AddField(
            model_name='taxonomyattribute',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyattribute',
            name='handle',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyvalue',
            name='handle',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyattribute',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyattribute',
            name='shopify_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomyvalue',
            name='shopify_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
