# Generated by Django 5.2.17 on 2026-08-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('approved', 'Approved'), ('manually_updated', 'Manually Updated')], db_index=True, default='pending', max_length=30)),
                ('requires_manual_review', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='taxonomy.taxonomycategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('rank', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_classifications', to='taxonomy.taxonomycategory')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_categories', to='classification.classification')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('classification', 'rank'), name='unique_alternative_category_rank')],
            },
        ),
        migrations.CreateModel(
            name='ClassificationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_attributes', to='taxonomy.taxonomyattribute')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='classification.classification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classification', 'attribute', 'value'), name='unique_classification_attribute_value')],
            },
        ),
    ]
